### ISSUE TITLE
"Original core authors:" in Readme.rst is missing a name...

### ISSUE THREAD

**Issue by isonno** [sarnold/urt#6]
It's nice to see this dusted off and preserved on Github!

I was one of the original creators of URT in the '80s, and created or co-created many of the tools.  Would be nice if you added my name back to the list of "Original core authors" at the end of Readme.rst

John W. Peterson
http://www.saccade.com/

**Comment by sarnold** [comment]
No problem, I'll take your word for it ;)  Note the .rst readme was just taken from the original and formatting added, etc (changes in latest commit).  Thanks for noticing!
